### ISSUE TITLE
Setup CD pipeline 

### ISSUE THREAD

**Issue by bayes343** [Fyord/fyord.dev#6]
- [x] Pick hosting platform
   - Firebase
   - Netlify 
- [x] Setup CI/CD GitHub action
   - Build, test, lint, deploy, etc.
- [x] Setup DNS for fyord.dev

**Comment by bayes343** [comment]
My personal preference is Firebase.  A little more granular with the options.

**Comment by justinhhorner** [comment]
+1 for Firebase
